Metrics/LineLength:
  Max: 100

Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/TrivialAccessors:
  AllowPredicates: true

Style/SignalException:
  EnforcedStyle: semantic
