language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile
sudo: false
cache: bundler
before_install:
  - gem install bundler
